[FIX] fieldservice_geoengine: increase delta for tests
Originally we tried 0.000_01, but this caused tests to fail from time to time,
causing errors like:

```
Traceback (most recent call last):
  File ".../fieldservice_geoengine/tests/test_fsm_location.py", line 63, in test_fsm_location_creation
    test_location_1.partner_latitude, 50.629980, delta=self.delta
AssertionError: 50.6298 != 50.62998 within 1e-05 delta
```

And fixes attempts like:
https://github.com/OCA/field-service/commit/935fb884